services:
  client:
    image: ghcr.io/clementvt/welcomer-client:latest
    container_name: welcomer-beta-client
    restart: unless-stopped
    pull_policy: always
    env_file: .env
    ports:
      - "127.0.0.1:3000:3000"
