services:
  client:
    image: ghcr.io/welcomer-bot/welcomer-client:${IMAGE_TAG:-latest}
    container_name: welcomer-beta-client
    restart: unless-stopped
    pull_policy: always
    env_file: .env
    ports:
      - "127.0.0.1:3000:3000"
