name: Deployment Workflow
permissions:
  contents: read
  packages: write

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Enable Corepack
        run: corepack enable

      - name: Prepare Yarn 4
        run: corepack prepare yarn@4.12.0 --activate
      
      - name: Configure Yarn for GitHub Packages
        run: |
          corepack enable
          yarn config set npmScopes.welcomer-bot.npmRegistryServer "https://npm.pkg.github.com"
          yarn config set npmScopes.welcomer-bot.npmAlwaysAuth true
          yarn config set npmScopes.welcomer-bot.npmAuthToken "${NODE_AUTH_TOKEN}"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Install dependencies
        run: yarn install --immutable

      - name: Build Next.js app
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
        run: yarn prisma generate && yarn build

      - name: SFTP Deploy
        uses: wlixcc/SFTP-Deploy-Action@v1.2.5
        with:
          username: ${{ secrets.USERNAME }} 
          server: ${{ secrets.HOST }}
          password: ${{ secrets.PASSWORD }}
          local_path: '.next/*'
          remote_path: '/var/www/welcomer-beta/client/.next'
          rsyncArgs: '--exclude=*.map'
          sftpArgs: '-o ConnectTimeout=5'

      - name: SSH Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd /var/www/welcomer-beta/client
            git pull
            yarn
            yarn prisma generate
            pm2 restart beta_client
